### ISSUE TITLE
mechanics

### ISSUE THREAD

**Issue by Bebruisk** [arealhero/mechanics#1]
Страница 20, в самом низу, опечатка
Должно быть d(tau)/d(sigma) * d(sigma)/dt вместо d(tau)/dt * d(sigma)/dt

**Comment by Bebruisk** [comment]
Страница 23, после 8.2, вопрос
Стоит ли добавить ссылки на доказательства (5.7) и (6.5)? 
Уверен, это будет неотъемлемая часть билета.

**Comment by arealhero** [comment]
Опечатку исправил, ссылки на формулы добавил.

Для доказательств созданы отдельные билеты (5 и 6 соответственно), поэтому мы можем пользоваться результатами уже проделанной работы.
